### ISSUE TITLE
BUG: certain file names cause error on upload

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/drive-project#66]
Probably caused due to elastic's indexing.
- [x] Create a hotfix for the bug.
- [ ] Create a permanent solution.

**Comment by AllKinds** [comment]
The change made at the api-gateway didn't fix the problem because it only handled media type uploads (and not multipart and resumable).
We agreed to make the patch in the `CreateFile` function of the search-service.

**Comment by nettashviro** [comment]
@yoavrozner  did you do that?

**Comment by yoavrozner** [comment]
I made fixed it in the UI. I can implement it in the gateway if necessary @Shahar-Y

**Comment by nettashviro** [comment]
Shahar-Y said closed it
