### ISSUE TITLE
Remove unused branches in all repositories

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/drive-project#71]
- [ ] web-ui
- [ ] api-gateway
- [ ] upload-service
- [ ] download-service
- [ ] file-service
- [ ] authentication-service
- [ ] user-service
- [ ] permission-service
- [ ] search-service
- [ ] spike-service
- [ ] delegation-service
- [ ] permit-service

**Comment by AllKinds** [comment]
created a new dupliacte (#94) by mistake.
