### ISSUE TITLE
KIDONS COMMENTS

### ISSUE THREAD

**Issue by ShragaUser** [meateam/drive-project#87]
you bad
this not good
this is i lose money

* file name change ( duplicate file endings )
* F2 - doesnt change file name
* ctrl + A on filename change is bad - very bad - super annoying - practically evil
* fast tab change kills logic and takes forever
* sometimes drive fails to load anymore and must enter again via incognito ( drive )

feature additions would be nice: 
* drag n drop
* send multiple files at once to "other network"

**Comment by AllKinds** [comment]
Hello @ShragaUser,

Thank you for your feedback!

Please open the relevant feature-requests/bugs in separate issues, created from the given templates, so we can address your issues more constructively.

**Comment by Shahar-Y** [comment]
I added the comments to https://github.com/meateam/drive-ui/issues/28
