### ISSUE TITLE
Add a deployment script

### ISSUE THREAD

**Issue by Shahar-Y** [meateam/drive-project#91]
The script receives a 7z file with .tar images inside it. 
There will be a way for choosing the version name for each service (could be a const).
The script will load, tag and push the images to the repo.

Additional options are great if you can think of some.
DOD: the script runs on the server

**Comment by nettashviro** [comment]
I saved the script on the kubernetes server ("...0001") under the "deploy-scripts" folder. Script name: image-load-and-push.sh
(if you can't find it for some reason, you can run linux command `locate image-load-and-push.sh`

**Comment by nettashviro** [comment]
noga approved the script :+1:
