### ISSUE TITLE
upgrade docker compose to v3

### ISSUE THREAD

**Issue by AllKinds** [meateam/drive-project#96]
upgrade docker compose to v3 in the following services:

- [x] api-gateway
- [x] authentication
- [x] delegation
- [x] download
- [x] file
- [ ] listener
- [x] permission
- [x] permit
- [x] search
- [ ] socket
- [x] spike
- [x] ui
- [x] upload
- [x] user

**Comment by Shahar-Y** [comment]
@nogahaskal well done. All current services have docker-compose-v3. Closing.
