### ISSUE TITLE
chore: delete unused packages and update dependencies

### ISSUE THREAD

**Issue by yonatandt** [meateam/drive-project#99]
Delete unused packages and update dependencies in all of the services in all of the following services:

- [x] api-gateway
- [x] authentication
- [ ] **delegation - need to change health check implementation in order to update dependencies**   
- [x] download - nothing to do :smile:
- [ ] **file - need to change health check implementation in order to update dependencies**   
- [x] listener - not relevant
- [x] permission
- [x] permit -  nothing to do :smile:
- [x] search
- [x] socket - not relevant 
- [ ] **spike - need to change health check implementation in order to update dependencies**   
- [x] ui
- [x] upload
- [ ] **user - need to change health check implementation in order to update dependencies**

**Comment by nettashviro** [comment]
:exclamation: opened an issue about healthcheck package update #115

**Comment by Shahar-Y** [comment]
Entered into master
